url: "https://onurozer.me"
title: "Onur Ozer" # the name of your site, e.g. ACME Corp.
description: "Marketer turned bootstrapper"

author:
  name: Onur Ozer

twitter:
  username: onurozer

permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path/

timezone: Asia/Singapore

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-inline-svg

# Make live reloading of css work by rebuilding the css everytime there's a change
postcss:
  cache: false

exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/onur-profile-square.jpg
  - scope:
      path: _pages/
    values:
      layout: default
  - scope:
      path: _posts/
    values:
      layout: post
