url: "https://onurozer.me"
title: "Onur Ozer" # the name of your site, e.g. ACME Corp.
description: "Marketer turned bootstrapper"

author:
  name: Onur Ozer
  twitter: https://twitter.com/onurozer
  linkedin: https://www.linkedin.com/in/onurozer/
  mastodon: http://ruby.social/@onurozer
  github: https://github.com/onurozer/

twitter:
  username: onurozer

permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path/

timezone: Asia/Singapore

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

# Make live reloading of css work by rebuilding the css everytime there's a change
postcss:
  cache: false

exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

defaults:
  - scope:
      path: _pages/
    values:
      layout: default
  - scope:
      path: _posts/
    values:
      layout: post
