url: "https://onurozer.me"
title: "Onur Ozer" # the name of your site, e.g. ACME Corp.
author:
  name: Onur Ozer
  twitter: onurozer
  github: onurozer
  linkedin: onurozer

timezone: Asia/Singapore

plugins:
  - jekyll-postcss

exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
